name = "Simples"
license = "MIT"
licenselink = "https://github.com/ssilva/hugo-theme-simples/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/ssilva/hugo-theme-simples/"
tags = ["Simple", "Clean", "Minimal", "Minimalist", "White", "Responsive", "Blog", "Google analytics", "Disqus"]
features = ["blog"]
min_version = "0.26"

[author]
  name = "Saulo Silva"
  homepage = "https://saulosilva.com/"
