baseURL = "https://example.com"
languageCode = "en"
title = "My Blog"
theme = "hugo-theme-simples"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
#disqusShortname = "XXXXXXXS"
#googleAnalytics = "UA-XXXXXX-X"

[params.simples]
    author = "John Smith" # Currently only used in <meta name="author">
    postsSectionHeader = "Articles"
